name: Check Listings

on:
  schedule:
    # 6:00–6:50 every 10 minutes
    - cron: '0-50/10 6 * * *'        # 6:00, 6:10, 6:20, 6:30, 6:40

    # 6:52–7:29 every 3 minutes
    - cron: '52-59/3 6 * * *'        # 6:52, 6:55, 6:58
    - cron: '0-29/3 7 * * *'         # 7:00 to 7:29

    # 7:30–11:19 every 10 minutes
    - cron: '30-59/10 7 * * *'       # 7:30, 7:40, 7:50
    - cron: '*/10 8-10 * * *'        # 8:00–10:59 (10-min)
    - cron: '0-10/10 11 * * *'       # 11:00, 11:10

    # 11:22–12:29 every 3 minutes
    - cron: '22-59/3 11 * * *'       # 11:22–11:59
    - cron: '0-29/3 12 * * *'        # 12:00–12:29

    # 12:30–14:30 every 10 minutes
    - cron: '30-59/10 12 * * *'      # 12:30, 12:40, 12:50
    - cron: '*/10 13 * * *'          # 13:00–13:59
    - cron: '0-30/10 14 * * *'       # 14:00, 14:10, 14:20, 14:30

  workflow_dispatch:  # Allows manual trigger

jobs:
  check-listings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run listings check
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python check_listings.py
      
    - name: Commit and push if seen_titles.txt changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Only stage seen_titles.txt, ignore other changes
        git add seen_titles.txt
        # Check if seen_titles.txt has changes
        git diff --staged --quiet || (git commit -m "Update seen_titles.txt" && git push)
