name: Check Listings

on:
  schedule:
    # Morning window (08:50-10:30 Amsterdam time, UTC+1/2)
    - cron: '2,12,22,32,42,52 6 * * *'   # 06:02, 06:12, 06:22, 06:32, 06:42, 06:52
    - cron: '2,12,22,32,42,52 7 * * *'   # 07:02, 07:12, 07:22, 07:32, 07:42, 07:52
    - cron: '2,12,22 8 * * *'            # 08:02, 08:12, 08:22
    # Afternoon window (13:00-15:00 Amsterdam time)
    - cron: '2,12,22,32,42,52 11 * * *'  # 11:02, 11:12, 11:22, 11:32, 11:42, 11:52
    - cron: '2,12,22,32,42,52 12 * * *'  # 12:02, 12:12, 12:22, 12:32, 12:42, 12:52
    - cron: '2,12,22 13 * * *'           # 13:02, 13:12, 13:22
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-listings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run listings check
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python check_listings.py
      
    - name: Commit and push if seen_titles.txt changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Only stage seen_titles.txt, ignore other changes
        git add seen_titles.txt
        # Check if seen_titles.txt has changes
        git diff --staged --quiet || (git commit -m "Update seen_titles.txt" && git push)
